name: "faim-dev deployment"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Login to Prefect Cloud 2.0
        run: |
          prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_FAIM_DEV_API_KEY }} 
          prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}

      - name: Build prefect deployment
        run: python ./deconvolution.py
